display:
  fullScreen: true
  bootImage: "./img/bootup.png"
processes:
  - name: Sleep Application
    preConditions:
      - name: Localhost
        type: network
        wait: true
        timeout: 30s
        attributes:
          - key: "hostPort"
            value: "localhost:8080"
    workDir: "/bin"
    command: "sleep"
    arguments:
      - "5"
    wait: false
    #waitMax: 50s
    restart: false
    environment:
      - key: FLAG1
        value: true